### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by delaaxe** [nabetse00/test-argent-wagmi-connector#1]
Nice! Can you add some actions to the demo dapp and redeploy to test that transactions actually work? Thanks in advance!

**Comment by nabetse00** [comment]
Ok ! 
I'll first add message signature... 
If there are some transactions types you are more interested in, please let me know !

**Comment by nabetse00** [comment]
Ok i've done:
- sign message example
- transaction send example

Do you need more ?

If there is any issues tell me !

![screenshot](https://raw.githubusercontent.com/nabetse00/test-argent-wagmi-connector/main/media/screenshot.png)

**Comment by delaaxe** [comment]
Great, thank you again!
